include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    file_names: false
    constant_identifier_names: false

analyzer:
  errors:
    curly_braces_in_flow_control_structures: error
    file_names: warning
    constant_identifier_names: warning
